### ISSUE TITLE
Possibly swapping to Tape

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/fizzbuzz#5]
Hi @skibinska! @finnhodgkin and I are running Testing Week for FAC11, and we want to switch to teaching Tape instead of QUnit. Would you be open to a PR swapping the QUnit syntax to Tape? We'd like to keep using the workshop as we thought it worked really well, and it wouldn't require much tweaking to work with Tape instead.

**Comment by skibinska** [comment]
Hi @oliverjam and @finnhodgkin! Yes, sure, no pronlem! :)

**Comment by oliverjam** [comment]
@skibinska We missed having a workshop like this in London, so I am refactoring it to use Tape so that Nazareth and Gaza can work teach this.

I'll have a PR ready in a minute

**Comment by jsms90** [comment]
@oliverjam Good work :+1: 

Happy to close this issue?
