### ISSUE TITLE
Remove most of the steps from the README

### ISSUE THREAD

**Issue by oliverjam** [foundersandcoders/fizzbuzz#8]
This workshop is intended to be used as a way for students to practice TDD after learning it in Learn Tape and the Roman Numerals Codealong. It might be better for them to have free reign to write their own code, rather than following along with the code in the readme (as they'll already have done this in the prior two workshops.

@skibinska Would you object to removing steps 2 and 3 from the readme? This way it would help them get their first test set up, then let them write everything themselves from then on.

**Comment by skibinska** [comment]
@oliverjam, no problem at all !

**Comment by jsms90** [comment]
@oliverjam How is this going?

**Comment by oliverjam** [comment]
@jsms90 Sorry! I was off Github all weekend and completely forgot about this. How did this go in Nazareth? Might still be worth doing for Gaza

**Comment by jsms90** [comment]
@oliverjam Haha don't be sorry :wink: 

@m4v15 @RQ16 ?

**Comment by zurda** [comment]
Hi @oliverjam , we're preparing for FAC-16 and saw this discussion. Is this about Roman Numerals or about Fizzbuzz? We'd love to address these comments and create a pull request, but this issue is in Fizzbuzz so I'm not sure which workshop it refers to. Can you clarify so we can improve it? :)

**Comment by oliverjam** [comment]
Hey @zurda, I think this was referring to this specific FizzBuzz repo, which we ended up replacing with the Roman Numerals codealong for FAC11. I don't know if this workshop has been used again since, sorry

**Comment by zurda** [comment]
That explains it, thanks @oliverjam !

**Comment by oliverjam** [comment]
So it looks like this repo is currently used as the initial introduction to Tape/TDD in the schedule. In that case I think this issue is no longer valid (I raised it when I was mentoring FAC11 and we had a pretty different structure to the first day).

I think it's actually good as it is—the readme gives enough hand-holding to communicate how TDD works but leaves enough work for the students to actually have to figure some stuff out.
